### ISSUE TITLE
Сделать модуль загрузки/скачивания контента (изображений, видео, доков)

### ISSUE THREAD

**Issue by andy-takker** [stackoverfollowers/ooc-hack#6]
Контент должен загружаться на отдельный роут `/contents` с именем и типом объекта. Ответ должен содержать `id` загруженного объекта. 

Также нужно сделать роут, по которому будет отдавать контент с сервера на скачивание `/contents/{id}` и роут для видео-стрима (с прошлого хакатона) `/contents/{id}/stream`.

Обработчики ошибок и прочее добавить.

**Comment by dogekiller21** [comment]
Имя и тип объекта содержится в метадате самого файла, fastapi подтягивает это сам
В ответ отдаю структуру
```
{
"id": 1
"name": file.docx,
"path": "static/123_file.docs"  (???? очень хочу изменить, хз как иначе картинки передавать на фронт)
"type": "DOCUMENT"
}
```
